import { beforeEach, describe, expect, it, vi } from 'vitest';

const { mockStartRequest, mockUpdateTaskName } = vi.hoisted(() => ({
  mockStartRequest: vi.fn(),
  mockUpdateTaskName: vi.fn(),
}));

vi.mock('../lib/evidence-model-request', () => ({ startEvidenceModelRequest: mockStartRequest }));
vi.mock('./tasks', () => ({ updateTaskName: mockUpdateTaskName }));

import { setStore } from './core';
import type { Task } from './types';
import { nameTaskWithModel } from './model-task-name';

function reply(text: string) {
  mockStartRequest.mockReturnValue({ result: Promise.resolve(text), cancel: vi.fn() });
}

beforeEach(() => {
  vi.clearAllMocks();
  setStore('modelTaskNames', true);
  setStore('taskNameModel', 'haiku');
  setStore('tasks', {
    t1: {
      id: 't1',
      name: 'how complicated would it be to',
      worktreePath: '/wt',
      nameIsAutoGenerated: true,
    } as Task,
  });
});

describe('nameTaskWithModel', () => {
  it('asks Luna through Codex at low effort when it is the chosen model', async () => {
    setStore('taskNameModel', 'luna');
    reply('Luna task naming');
    await nameTaskWithModel('t1', 'name tasks with luna');
    expect(mockStartRequest).toHaveBeenCalledWith(
      expect.objectContaining({
        settings: expect.objectContaining({
          provider: 'codex',
          model: 'gpt-6-luna',
          effort: 'low',
        }),
      }),
    );
    expect(mockUpdateTaskName).toHaveBeenCalledWith('t1', 'Luna task naming');
  });

  it('renames an auto-named task with the model title', async () => {
    reply('Haiku task naming');
    await nameTaskWithModel('t1', 'how complicated would it be to name tasks with haiku');
    expect(mockStartRequest).toHaveBeenCalledWith(
      expect.objectContaining({
        purpose: 'task-name',
        cwd: '/wt',
        settings: expect.objectContaining({ provider: 'claude', model: 'haiku' }),
      }),
    );
    expect(mockUpdateTaskName).toHaveBeenCalledWith('t1', 'Haiku task naming');
  });

  it('does nothing when the setting is off', async () => {
    setStore('modelTaskNames', false);
    await nameTaskWithModel('t1', 'prompt');
    expect(mockStartRequest).not.toHaveBeenCalled();
  });

  it('keeps a name the user changed while the model was answering', async () => {
    reply('Haiku task naming');
    const pending = nameTaskWithModel('t1', 'prompt');
    setStore('tasks', 't1', 'nameIsAutoGenerated', false);
    await pending;
    expect(mockUpdateTaskName).not.toHaveBeenCalled();
  });

  it('keeps the title of a task opened from Super Productivity', async () => {
    setStore('tasks', 't1', 'superProductivity', { taskId: 'sp1', syncedTitle: 'SP title' });
    await nameTaskWithModel('t1', 'prompt');
    expect(mockStartRequest).not.toHaveBeenCalled();
  });

  it('leaves a task closed while the model was answering', async () => {
    reply('Haiku task naming');
    const pending = nameTaskWithModel('t1', 'prompt');
    setStore('tasks', 't1', undefined as unknown as Task);
    await pending;
    expect(mockUpdateTaskName).not.toHaveBeenCalled();
  });

  it('keeps the heuristic name when the reply holds no title', async () => {
    reply('  \n');
    await nameTaskWithModel('t1', 'prompt');
    expect(mockUpdateTaskName).not.toHaveBeenCalled();
  });

  it('keeps the heuristic name when the model fails', async () => {
    mockStartRequest.mockReturnValue({
      result: Promise.reject(new Error('claude not found')),
      cancel: vi.fn(),
    });
    await expect(nameTaskWithModel('t1', 'prompt')).resolves.toBeUndefined();
    expect(mockUpdateTaskName).not.toHaveBeenCalled();
  });
});
