import {
  TASK_NAME_MODELS,
  buildTaskNamePrompt,
  parseModelTaskName,
} from '../../electron/shared/task-name-model';
import { startEvidenceModelRequest } from '../lib/evidence-model-request';
import { warn as logWarn } from '../lib/log';
import { store } from './core';
import { updateTaskName } from './tasks';

/**
 * Replaces a prompt-derived task name with a short title from the chosen cheap
 * model (Haiku or Luna), when the user opted in. The task starts with the heuristic name, so this never delays
 * creation; the branch keeps that name, since renaming a live worktree's
 * branch would pull it out from under the running agent.
 *
 * A task opened from Super Productivity is already linked here and keeps that
 * task's title. One created here links later and receives the model title
 * through the usual rename sync.
 */
export async function nameTaskWithModel(taskId: string, prompt: string): Promise<void> {
  const task = store.tasks[taskId];
  if (!store.modelTaskNames || !prompt.trim() || !task?.worktreePath) return;
  if (task.superProductivity) return;
  try {
    const reply = await startEvidenceModelRequest({
      prompt: buildTaskNamePrompt(prompt),
      cwd: task.worktreePath,
      settings: TASK_NAME_MODELS[store.taskNameModel],
      agentEnvFiles: store.agentEnvFiles,
      purpose: 'task-name',
    }).result;
    const name = parseModelTaskName(reply);
    // The user may have renamed or closed the task while the model was answering.
    if (name && store.tasks[taskId]?.nameIsAutoGenerated) updateTaskName(taskId, name);
  } catch (err) {
    logWarn('tasks', 'Model task naming failed; keeping the prompt-derived name', {
      err: String(err),
    });
  }
}
